// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzahxvazbthyjjzugxsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6YWh4dmF6YnRoeWpqenVneHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTg2MTgsImV4cCI6MjA1MDYzNDYxOH0.0IhzGCqwNYnv44pSQQ4Mt2D83Mz0Ehzd0dmBNPig0Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);